services:
  order-db:
    image: postgres:16-alpine
    container_name: sio-order-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sio-order-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - order-internal
    restart: unless-stopped

  order-service:
    image: faizms14/sio-order-service:latest
    container_name: sio-order-service
    env_file:
      - .env
    networks:
      - order-internal
      - sio-net
      - proxy_net
    depends_on:
      order-db:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy_net
      traefik.http.routers.sio-order.rule: "Host(`api-sioms.faizms.com`) && PathPrefix(`/orders`)"
      traefik.http.routers.sio-order.entrypoints: websecure
      traefik.http.routers.sio-order.tls: "true"
      traefik.http.routers.sio-order.tls.certresolver: myresolver
      traefik.http.services.sio-order.loadbalancer.server.port: "3003"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: sio-order-adminer
    # ports:
    #   - "8083:8080"
    depends_on:
      - order-db
    networks:
      - sio-net

volumes:
  sio-order-db-data:
networks:
  order-internal:
    name: sio-order-internal
  sio-net:
    external: true
  proxy_net:
    external: true
